		void	*mlx;
		void	*mlx_win;
		t_data	img;
		printf("%s", *argv);
		mlx = mlx_init();
		mlx_win = mlx_new_window(mlx, 1920, 1080, "So_long");
    	img.img = mlx_new_image(mlx, 1920, 1080);
		img.addr = mlx_get_data_addr(img.img, &img.bits_per_pixels, &img.line_lenght, &img.endian);
		mlx_put_image_to_window(mlx, mlx_win, img.img, 0, 0);
		mlx_loop(mlx);